# Generated by Django 4.2.7 on 2023-11-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chain_id", models.IntegerField(unique=True)),
                ("chain_symbol", models.CharField(max_length=255, unique=True)),
                ("chain_name", models.CharField(max_length=255)),
                ("chain_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RPCUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("chain_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="evm.chain")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_address", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("contract_name", models.CharField(blank=True, max_length=255, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("creator", models.CharField(blank=True, max_length=255, null=True)),
                ("compiler_version", models.CharField(blank=True, max_length=50, null=True)),
                ("contract_type", models.CharField(blank=True, max_length=50, null=True)),
                ("contract_abi", models.JSONField(blank=True, null=True)),
                ("contract_code", models.TextField(blank=True, null=True)),
                ("contract_description", models.TextField(blank=True, null=True)),
                (
                    "chain_id",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="evm.chain"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
